"""Engineering core for BOEF analysis."""

from core.analysis import AnalysisInputs, AnalysisResult, compute_track_response
from core.foundation_profiles import ramp_profile, step_profile
from core.model import (
    PointLoad,
    beam_parameter_beta,
    contraflexure_distance,
    compute_deflection,
    deflection_at,
    max_deflection_single_load,
    max_moment_single_load,
    moment_at,
    rail_base_stress,
    rail_seat_load_from_deflection,
    reaction_at,
    shear_at,
    sleeper_seat_loads,
    zero_moment_distance,
)
from core.solver import (
    StaticBeamSolution,
    TwoRailSolution,
    build_discrete_supports,
    equivalent_continuous_modulus,
    solve_static_beam_fdm,
    solve_two_rail_static_fdm,
)
from core.track_modulus import (
    TrackModulusEstimate,
    back_calculate_modulus_single_point,
    compute_deflection_profile,
    estimate_track_modulus_deflection_area,
    estimate_track_modulus_deflection_area_delta,
    estimate_track_modulus_single_deflection,
    synthesize_track_modulus_from_springs,
    track_modulus_from_deflection,
    track_modulus_from_spring_constant,
    track_spring_constant_from_deflection,
)
from core.units import (
    kn_to_n,
    kpa_to_pa,
    m3_to_mm3,
    m4_to_mm4,
    mm3_to_m3,
    mm4_to_m4,
    mm_to_m,
    m_to_mm,
    mpa_to_pa,
    n_to_kn,
    pa_to_kpa,
    pa_to_mpa,
)

__all__ = [
    "AnalysisInputs",
    "AnalysisResult",
    "compute_track_response",
    "PointLoad",
    "beam_parameter_beta",
    "contraflexure_distance",
    "compute_deflection",
    "deflection_at",
    "max_deflection_single_load",
    "max_moment_single_load",
    "moment_at",
    "rail_base_stress",
    "rail_seat_load_from_deflection",
    "reaction_at",
    "shear_at",
    "sleeper_seat_loads",
    "zero_moment_distance",
    "StaticBeamSolution",
    "TwoRailSolution",
    "build_discrete_supports",
    "equivalent_continuous_modulus",
    "solve_static_beam_fdm",
    "solve_two_rail_static_fdm",
    "TrackModulusEstimate",
    "back_calculate_modulus_single_point",
    "compute_deflection_profile",
    "estimate_track_modulus_deflection_area",
    "estimate_track_modulus_deflection_area_delta",
    "estimate_track_modulus_single_deflection",
    "synthesize_track_modulus_from_springs",
    "track_modulus_from_deflection",
    "track_modulus_from_spring_constant",
    "track_spring_constant_from_deflection",
    "ramp_profile",
    "step_profile",
    "kn_to_n",
    "kpa_to_pa",
    "m3_to_mm3",
    "m4_to_mm4",
    "mm3_to_m3",
    "mm4_to_m4",
    "mm_to_m",
    "m_to_mm",
    "mpa_to_pa",
    "n_to_kn",
    "pa_to_kpa",
    "pa_to_mpa",
]
