"""Help content for the BOEF application."""

from __future__ import annotations


def build_help_markdown() -> str:
    return (
        "# BOEF Help\n"
        "\n"
        "## What this app does\n"
        "This tool computes rail responses for a beam on elastic foundation (BOEF) and provides\n"
        "static, quasi-static envelope, and dynamic analysis workflows for railway track.\n"
        "\n"
        "## Core engineering assumptions\n"
        "- Linear elasticity only.\n"
        "- Superposition for multiple point loads.\n"
        "- Closed-form static uses an infinite beam on Winkler foundation.\n"
        "- Numerical static uses finite-difference with optional extensions (Pasternak, discrete supports,\n"
        "  two-rail coupling, Timoshenko beam).\n"
        "- Transition-energy metrics are post-processing only (solver equations are unchanged).\n"
        "\n"
        "## Recent UI additions\n"
        "- Static charts now include compact critical labels for max/min, zero-crossings, and key\n"
        "  curve intersections where applicable.\n"
        "- Critical labels use transparent callouts and auto-scale with chart size.\n"
        "- Custom charts retain critical labels after rendering from selected source series.\n"
        "- Transition energy outputs are shown only when Winkler semantics apply.\n"
        "- Stress chart added across analysis modes (rail bending stress always; ballast/capping where supported).\n"
        "\n"
        "## Load convention\n"
        "- Manual single and multiple wheel loads are interpreted as wheel loads already acting on one rail.\n"
        "- Train/axle builder and AS5100 inputs are interpreted as total axle loads. The solver applies half\n"
        "  of each axle load to each rail line, so a 360 kN axle is analysed as 180 kN per rail.\n"
        "- Chart load arrows and metadata show both values for axle-based sources: axle load and wheel load per rail.\n"
        "- AS5100 outputs do not include automatic dynamic allowance unless a separate design factor is applied.\n"
        "\n"
        "## Governing equations (static)\n"
        "Winkler foundation:\n"
        "  EI * w''''(x) + k * w(x) = sum(P_i * delta(x - x_i))\n"
        "\n"
        "Beam parameter:\n"
        "  beta = (k / (4*E*I))^(1/4)\n"
        "\n"
        "Rail support reaction:\n"
        "  R_support(x) = k * w(x)\n"
        "  This is the support line reaction acting on the rail, not ballast pressure.\n"
        "\n"
        "Moment / Shear:\n"
        "  M(x) = E*I * w''(x)\n"
        "  V(x) = dM/dx\n"
        "\n"
        "A3902 quasi-static dynamic factor (Eisenmann form):\n"
        "  phi = 1 + delta * eta * t_c\n"
        "  eta = 1.0                      for V <= 60 km/h\n"
        "  eta = 1.0 + (V - 60) / 140     for V > 60 km/h\n"
        "  P_DV = P_SV * phi\n"
        "\n"
        "A3902 static design checks (summary only, SI internally):\n"
        "  y_max = P_DV * beta / (2k)\n"
        "  Q_R = F1 * S * k * y_max\n"
        "  P_A = F2 * Q_R / (B * L_eff)\n"
        "  P_F = P_A * [1 - z^3 / (A_eq + z^2)^(1.5)]  (z = Z_B)\n"
        "  P_S = P_A * [1 - z^3 / (A_eq + z^2)^(1.5)]  (z = Z_B + Z_F)\n"
        "where A_eq = (B * L_eff) / pi.\n"
        "\n"
        "## Static analysis modes\n"
        "### Static (single position)\n"
        "- Solves one load case at the given positions.\n"
        "- Closed-form if Advanced solver is OFF.\n"
        "- Numerical FDM if Advanced solver is ON.\n"
        "\n"
        "### Quasi-static Envelope (Closed-form)\n"
        "- Treats load positions as offsets from x_ref.\n"
        "- Slides the load group over a movement range and builds max/min envelopes.\n"
        "- Movement range is applied relative to the reference x_ref input.\n"
        "- Uses the closed-form Winkler solution only.\n"
        "- Two-rail coupling is not available in this mode.\n"
        "\n"
        "### Quasi-static Envelope (Advanced static)\n"
        "- Same envelope logic but uses the numerical solver at each step.\n"
        "- Supports discrete supports, nonuniform k(x), Pasternak, and two-rail coupling.\n"
        "- Nonuniform foundation mode must use Step or Ramp profile.\n"
        "\n"
        "### Transition zones (Design metrics)\n"
        "- Adds transition-specific metrics on top of static or envelope results.\n"
        "- Lets you define k(x) profiles (step/ramp/exponential/segment) for stiffness changes.\n"
        "- Reports differential deflection, curvature, reaction gradient, and energy indices.\n"
        "- Envelope run mode uses the movement range relative to the x_ref input.\n"
        "- Templates/presets are starting points; confirm values against project data.\n"
        "\n"
        "## Foundation models (numerical static)\n"
        "- Winkler (single-layer): uses k directly.\n"
        "- Series (railpad + trackbed): converts pad/bed stiffness to per-length and uses\n"
        "  equivalent series stiffness k_eq = (k_pad*k_bed)/(k_pad + k_bed).\n"
        "- Sleeper-mass: static equivalent stiffness (mass ignored in static).\n"
        "- Optional Pasternak shear layer input `k_g` defaults to 10,000 kN when enabled.\n"
        "- Pasternak is not supported with Timoshenko beam mode.\n"
        "\n"
        "## Two-rail coupled interpretation\n"
        "- If left and right rail loads are symmetric, two-rail coupling may look very similar to single-rail\n"
        "  on the main static charts because differential rail deflection is small.\n"
        "- Use `Rail deflection (L/R)` and `Rail moment (L/R)` tabs to inspect coupling behavior directly.\n"
        "- To expose coupling transfer effects, enable asymmetric right-rail load and compare L/R traces.\n"
        "\n"
        "## Dynamic modes\n"
        "- Steady-state moving load (travelling wave solution): spatial response in the moving coordinate frame.\n"
        "- FFT/PSD charts are the separate frequency-domain outputs.\n"
        "- Time-history (explicit): time-domain response with probes.\n"
        "- Dipped joint: separate wheel/rail force model, not a track deflection solver.\n"
        "\n"
        "## How to interpret outputs\n"
        "- Deflection w(x): vertical rail displacement (use max |w| for design checks).\n"
        "- Moment M(x): bending moment; sign follows solver convention.\n"
        "- Shear V(x): shear force; sign follows solver convention.\n"
        "- Rail support reaction R_support(x): continuous Winkler support reaction per rail length, acting on the rail. It is not the ballast pressure.\n"
        "- Sleeper loads: integrated rail support reaction over the sleeper tributary length.\n"
        "- Sleeper-ballast contact pressure: sleeper load / (sleeper length * width), representing pressure at the top of ballast.\n"
        "- Stress chart (single MPa axis):\n"
        "  Rail stress - top fibre (bending): sigma_top = M / Z_top.\n"
        "  Rail stress - bottom fibre (bending): sigma_bottom = -M / Z_bottom.\n"
        "  Ballast pressure: q_ballast = Q / (B*L).\n"
        "  Capping pressure (2:1 spread, load-conserving):\n"
        "    Q = q_ballast*(B*L),\n"
        "    q_capping = Q / ((B + 2h_b)*(L + 2h_b)).\n"
        "  Positive pressure convention is compressive.\n"
        "  Dynamic mode reports peak rail bending stress only; sleeper/capping pressures are unavailable.\n"
        "  Ballast/capping curves are usually much smaller than rail bending stresses on the same axis.\n"
        "- Envelope results: max/min curves over all load positions.\n"
        "- Transition metrics: summarize stiffness-change severity for design comparisons.\n"
        "- Chart labels: compact callouts mark critical locations (max/min/x0/intersections) for\n"
        "  quick interpretation and review.\n"
        "\n"
        "## Transition metrics (design interpretation)\n"
        "- Δw(s): differential deflection over one sleeper spacing (geometry sensitivity).\n"
        "- Δw(1 m): normalized deflection differential (comparison index).\n"
        "- κ_max and M_max: curvature/bending severity (fatigue proxy).\n"
        "- U_b: bending strain energy (global demand indicator).\n"
        "- max |dp/dx|: reaction gradient (abrupt support transfer proxy).\n"
        "- max sleeper load: peak tributary reaction (maintenance sensitivity).\n"
        "- Energy metrics (Winkler static):\n"
        "  u_r(x)=M(x)^2/(2EI), u_f(x)=0.5*k(x)*w(x)^2, u=u_r+u_f.\n"
        "  U_r, U_f and U_total are integrals of densities over x.\n"
        "  η=U_f/U_total indicates support-vs-rail energy partitioning.\n"
        "  max |du/dx| and windowed energy flag abrupt local energy transfer.\n"
        "- Non-Winkler transition runs do not emit Winkler energy metrics.\n"
        "- k(x) is entered and reported as MN/m², then converted to N/m² internally; q_f(x)=k(x)w(x) in N/m.\n"
        "- Envelope energy values are conservative upper-bound proxies using\n"
        "  max(|M_max|,|M_min|) and max(|w_max|,|w_min|) at each x.\n"
        "- If an energy peak appears at a domain boundary, extend/check the analysis domain.\n"
        "\n"
        "## Ballast and formation stress (envelope)\n"
        "2:1 spread model:\n"
        "  sigma_z(z) = q_b * (B0*L0) / ((B0+2z)*(L0+2z))\n"
        "where q_b is ballast pressure and B0/L0 are effective bearing dimensions.\n"
        "Ballast thickness input defaults to 300 mm and is used as h_b in stress post-processing.\n"
        "\n"
        "## Units\n"
        "- Internal units are SI: m, N, Pa, N*m.\n"
        "- UI may use kN, mm, MPa; conversion happens once at input boundaries.\n"
        "\n"
        "## Exports\n"
        "- Static analysis CSV appends rail stress columns:\n"
        "  sigma_top_fiber_pa, sigma_bottom_fiber_pa.\n"
        "- Static sleeper CSV appends stress/pressure columns:\n"
        "  ballast_pressure_signed_pa, ballast_pressure_comp_pa,\n"
        "  capping_pressure_signed_pa, capping_pressure_comp_pa.\n"
        "- Envelope analysis CSV appends:\n"
        "  sigma_top_fiber_ub_pa, sigma_bottom_fiber_ub_pa.\n"
        "- Envelope sleeper CSV appends:\n"
        "  ballast_pressure_max_comp_pa, capping_pressure_max_comp_pa,\n"
        "  capping_pressure_signed_max_pa, capping_pressure_signed_min_pa.\n"
        "- Transition metrics CSV: design metrics summary.\n"
        "- Transition series CSV: k(x) and response series for plotting.\n"
        "- Metadata sidecars include stress assumptions:\n"
        "  stress_schema_version, ballast_thickness_m,\n"
        "  stress_model, bearing_geometry_provenance, pressure_sign_convention.\n"
        "\n"
        "## Scope limits\n"
        "- Stress chart values are elastic bending stresses and support pressures only.\n"
        "- Wheel/rail contact stress is not included.\n"
        "- Ballast shear stress is not included.\n"
        "- 2:1 spread is an engineering approximation for vertical stress diffusion.\n"
    )


def build_dynamic_chart_help_markdown(chart_id: str) -> str:
    """Return chart-specific help text for dynamic plots."""
    chart_help = {
        "dynamic_deflection": (
            "# Dynamic Deflection (`w(ξ)`)\n"
            "\n"
            "## What it shows\n"
            "- Vertical rail displacement in the moving coordinate `ξ`.\n"
            "- Units are millimetres (mm).\n"
            "- Peaks identify where the moving load creates maximum track deformation.\n"
            "\n"
            "## Engineering interpretation\n"
            "- Use peak `|w|` to assess ride quality risk and serviceability margin.\n"
            "- Compare overlays to evaluate how speed, damping, and support stiffness shift peak response.\n"
            "- Larger `|w|` generally indicates higher bending and support demand.\n"
            "\n"
            "## Practical use\n"
            "- Screen candidate support profiles before detailed design.\n"
            "- Check if stiffness transitions reduce peak displacement under the same load model.\n"
        ),
        "dynamic_moment": (
            "# Dynamic Bending Moment (`M(ξ)`)\n"
            "\n"
            "## What it shows\n"
            "- Rail bending moment distribution in the moving frame.\n"
            "- Units are kN·m.\n"
            "\n"
            "## Engineering interpretation\n"
            "- Peak `|M|` is a primary indicator of rail bending stress demand.\n"
            "- Compare overlays to see if parameter changes reduce moment hotspots.\n"
            "- Sign changes indicate alternating sagging/hogging regions.\n"
            "\n"
            "## Practical use\n"
            "- Support fatigue-oriented decisions and stress checks.\n"
            "- Benchmark dynamic demand trends against static baseline expectations.\n"
        ),
        "dynamic_shear": (
            "# Dynamic Shear (`V(ξ)`)\n"
            "\n"
            "## What it shows\n"
            "- Rail shear force distribution in the moving frame.\n"
            "- Units are kN.\n"
            "\n"
            "## Engineering interpretation\n"
            "- Local spikes in `|V|` indicate sharper load transfer through the rail.\n"
            "- Changes in damping/support properties can shift both magnitude and location of shear peaks.\n"
            "\n"
            "## Practical use\n"
            "- Identify sections where connections/details may see elevated shear demand.\n"
            "- Compare alternatives for smoother force transfer.\n"
        ),
        "dynamic_reaction": (
            "# Dynamic Rail Support Reaction (`R_support(ξ)`)\n"
            "\n"
            "## What it shows\n"
            "- Continuous rail support reaction per unit rail length along the moving coordinate.\n"
            "- This is the reaction acting on the rail from the support model, not the pressure under the ballast.\n"
            "- Units are kN/m.\n"
            "\n"
            "## Engineering interpretation\n"
            "- Higher peaks imply stronger support demand and potentially faster support deterioration.\n"
            "- Overlay comparisons reveal how stiffness and damping redistribute support loading.\n"
            "\n"
            "## Practical use\n"
            "- Evaluate support profile suitability and relative maintenance risk.\n"
            "- Cross-check with sleeper-seat load trends for consistency.\n"
        ),
        "dynamic_damping": (
            "# Damping Force Time History (`F_d(t)`)\n"
            "\n"
            "## What it shows\n"
            "- Time-domain damping force response at the selected probe.\n"
            "- Units are kN/m.\n"
            "\n"
            "## Engineering interpretation\n"
            "- Indicates how much response is dissipated by damping mechanisms.\n"
            "- Stronger damping generally reduces sustained oscillations and spectral peaks.\n"
            "\n"
            "## Practical use\n"
            "- Tune damping assumptions and compare viscous vs hysteretic settings.\n"
            "- Verify response decay behavior remains physically plausible.\n"
        ),
        "dynamic_time": (
            "# Deflection Time History (`w(t)`)\n"
            "\n"
            "## What it shows\n"
            "- Probe-based displacement history over time.\n"
            "- Units are mm.\n"
            "\n"
            "## Engineering interpretation\n"
            "- Captures transient behavior, pass-by peaks, and decay trends.\n"
            "- Useful for seeing whether a configuration has smoother or more oscillatory response.\n"
            "\n"
            "## Practical use\n"
            "- Compare operating scenarios at specific track locations.\n"
            "- Use alongside FFT/PSD to connect time-domain events to frequency content.\n"
        ),
        "dynamic_fft": (
            "# FFT Amplitude (`|W(f)|`)\n"
            "\n"
            "## What it shows\n"
            "- Single-sided frequency amplitude spectrum at the selected probe.\n"
            "- Units are mm.\n"
            "\n"
            "## Engineering interpretation\n"
            "- Highlights dominant response frequencies.\n"
            "- Overlay shifts in peak frequency/amplitude indicate sensitivity to speed, damping, or stiffness.\n"
            "\n"
            "## Practical use\n"
            "- Identify frequencies to monitor in instrumentation campaigns.\n"
            "- Support design decisions intended to avoid problematic excitation bands.\n"
        ),
        "dynamic_psd": (
            "# Power Spectral Density (PSD)\n"
            "\n"
            "## What it shows\n"
            "- Distribution of displacement response energy with frequency.\n"
            "- Units are mm²/Hz.\n"
            "\n"
            "## Engineering interpretation\n"
            "- Broad/high PSD regions indicate stronger vibration energy in those bands.\n"
            "- Overlay comparisons help rank alternatives for vibration mitigation.\n"
            "\n"
            "## Practical use\n"
            "- Evaluate comfort/maintenance-oriented frequency bands.\n"
            "- Complement FFT by emphasizing energy rather than just amplitude peaks.\n"
        ),
        "dynamic_impedance": (
            "# Support Impedance Magnitude (`|Z(f)|`)\n"
            "\n"
            "## What it shows\n"
            "- Frequency-dependent support impedance magnitude at the selected probe.\n"
            "- Units are MN/m².\n"
            "\n"
            "## Engineering interpretation\n"
            "- Higher impedance means stronger opposition to motion at that frequency.\n"
            "- Frequency trends reveal how support dynamic properties filter excitation.\n"
            "\n"
            "## Practical use\n"
            "- Compare support concepts for targeted vibration control.\n"
            "- Interpret with FFT/PSD to understand response-driving and response-limiting bands.\n"
        ),
    }
    return chart_help.get(
        chart_id,
        (
            "# Dynamic Chart Help\n"
            "\n"
            "No chart-specific help is available for this item yet.\n"
        ),
    )
